[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
